# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: /home/quartus/workspace/LPSC/constr/Nexys-Video-Master.xdc

# IP: ip/blk_mem_iter/blk_mem_iter.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==blk_mem_iter || ORIG_REF_NAME==blk_mem_iter} -quiet] -quiet
