# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/joco/Documents/cours/FPGA/master/nexys_video/mse_mandelbrot/mse_mandelbrot.srcs/sources_1/ip/clk_vga_640x480/clk_vga_640x480.xci
# IP: The module: 'clk_vga_640x480' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/joco/Documents/cours/FPGA/master/nexys_video/mse_mandelbrot/mse_mandelbrot.srcs/sources_1/ip/clk_vga_640x480/clk_vga_640x480_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_vga_640x480'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: /home/joco/Documents/cours/FPGA/master/nexys_video/mse_mandelbrot/mse_mandelbrot.srcs/sources_1/ip/clk_vga_640x480/clk_vga_640x480.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_vga_640x480'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: /home/joco/Documents/cours/FPGA/master/nexys_video/mse_mandelbrot/mse_mandelbrot.srcs/sources_1/ip/clk_vga_640x480/clk_vga_640x480_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_vga_640x480'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: /home/joco/Documents/cours/FPGA/master/nexys_video/mse_mandelbrot/mse_mandelbrot.srcs/sources_1/ip/clk_vga_640x480/clk_vga_640x480.xci
# IP: The module: 'clk_vga_640x480' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/joco/Documents/cours/FPGA/master/nexys_video/mse_mandelbrot/mse_mandelbrot.srcs/sources_1/ip/clk_vga_640x480/clk_vga_640x480_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_vga_640x480'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: /home/joco/Documents/cours/FPGA/master/nexys_video/mse_mandelbrot/mse_mandelbrot.srcs/sources_1/ip/clk_vga_640x480/clk_vga_640x480.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_vga_640x480'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: /home/joco/Documents/cours/FPGA/master/nexys_video/mse_mandelbrot/mse_mandelbrot.srcs/sources_1/ip/clk_vga_640x480/clk_vga_640x480_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_vga_640x480'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
