# 
# Synthesis run script generated by Vivado
# 

proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
set_param xicom.use_bs_reader 1
set_msg_config  -ruleid {10}  -id {Constraints 18-619}  -string {{WARNING: [Constraints 18-619] A clock with name 'ClkSys100MhzxC' already exists, overwriting the previous clock with the same name. [/home/joco/Documents/cours/FPGA/master/nexys_video/mse_mandelbrot/mse_mandelbrot.runs/synth_1/.Xil/Vivado-25469-t450s-debian/dcp5/clk_hdmi_1024x600_in_context.xdc:1]}}  -suppress 
set_msg_config  -ruleid {11}  -id {Timing 38-316}  -string {{WARNING: [Timing 38-316] Clock period '20.000' specified during out-of-context synthesis of instance 'BramVideoMemory1024x768x9xI' at clock pin 'clka' is different from the actual clock period '19.531', this can lead to different synthesis results.}}  -suppress 
set_msg_config  -ruleid {12}  -id {Synth 8-3917}  -string {{WARNING: [Synth 8-3917] design mse_mandelbrot has port HdmiTxRsclxSO driven by constant 1}}  -suppress 
set_msg_config  -ruleid {13}  -id {Synth 8-3331}  -string {{WARNING: [Synth 8-3331] design vga_to_hdmi has unconnected port HdmiSourcexDIO[HdmiSourceInxS][HdmiTxHpdxS]}}  -suppress 
set_msg_config  -ruleid {14}  -id {Synth 8-3332}  -string {{WARNING: [Synth 8-3332] Sequential element (ImageGeneratorxI/DataxD_reg[20]) is unused and will be removed from module mse_mandelbrot.}}  -suppress 
set_msg_config  -ruleid {15}  -id {Synth 8-565}  -string {{WARNING: [Synth 8-565] redefining clock 'ClkSys100MhzxC'}}  -suppress 
set_msg_config  -ruleid {16}  -id {Shape Builder 18-119}  -string {{CRITICAL WARNING: [Shape Builder 18-119] Failed to create I/OLOGIC Route Through shape for instance HdmixI/ClkVgaHdmi1024x600xG.ClkVga1024x600xI/inst/clkin1_ibufg. Found overlapping instances within the shape: HdmixI/ClkVgaHdmi1024x600xG.ClkHdmi1024x600xI/inst/clkin1_ibufg and HdmixI/ClkVgaHdmi1024x600xG.ClkVga1024x600xI/inst/clkin1_ibufg.}}  -suppress 
set_msg_config  -ruleid {17}  -id {Constraints 18-619}  -string {{WARNING: [Constraints 18-619] A clock with name 'ClkSys100MhzxC' already exists, overwriting the previous clock with the same name. [/home/joco/Documents/cours/FPGA/master/nexys_video/mse_mandelbrot/mse_mandelbrot.srcs/sources_1/ip/clk_hdmi_1024x600/clk_hdmi_1024x600.xdc:56]}}  -suppress 
set_msg_config  -ruleid {18}  -id {Vivado 12-1411}  -string {{CRITICAL WARNING: [Vivado 12-1411] Cannot set LOC property of ports, Cannot set PACKAGE_PIN property of ports,  port ClkSys100MhzxC can not be placed on PACKAGE_PIN R4 because the PACKAGE_PIN is occupied by port ClkSys100MhzxC [/home/joco/Documents/cours/FPGA/master/nexys_video/mse_mandelbrot/constr/Nexys-Video-Master.xdc:8]}}  -suppress 
set_msg_config  -ruleid {19}  -id {DRC CHECK-3}  -string {{WARNING: [DRC CHECK-3] Report rule limit reached: REQP-1839 rule limit reached: 20 violations have been found.}}  -suppress 
set_msg_config  -ruleid {20}  -id {DRC REQP-1839}  -string {{WARNING: [DRC REQP-1839] RAMB36 async control check: The RAMB36E1 BramVideoMemory1024x768x9xI/U0/inst_blk_mem_gen/gnbram.gnativebmg.native_blk_mem_gen/valid.cstr/ramloop[0].ram.r/prim_noinit.ram/DEVICE_7SERIES.NO_BMM_INFO.TRUE_DP.SIMPLE_PRIM36.ram has an input control pin BramVideoMemory1024x768x9xI/U0/inst_blk_mem_gen/gnbram.gnativebmg.native_blk_mem_gen/valid.cstr/ramloop[0].ram.r/prim_noinit.ram/DEVICE_7SERIES.NO_BMM_INFO.TRUE_DP.SIMPLE_PRIM36.ram/ADDRARDADDR[10] (net: BramVideoMemory1024x768x9xI/U0/inst_blk_mem_gen/gnbram.gnativebmg.native_blk_mem_gen/valid.cstr/ramloop[0].ram.r/prim_noinit.ram/addra[7]) which is driven by a register (HdmixI/VgaxI/VgaControlerxI/HCountxD_reg[7]) that has an active asychronous set or reset. This may cause corruption of the memory contents and/or read values when the set/reset is asserted and is not analyzed by the default static timing analysis. It is suggested to eliminate the use of a set/reset to registers driving this RAMB pin or else use a synchronous reset in which the assertion of the reset is timed by default.}}  -suppress 
set_msg_config  -ruleid {21}  -id {Place 30-58}  -string {{ERROR: [Place 30-58] IO placement is infeasible. Number of unplaced terminals (1) is greater than number of available sites (0).
The following are banks with available pins: 
 IO Group: 0 with : SioStd: LVCMOS18   VCCO = 1.8 Termination: 0  TermDir:  In   RangeId: 1 GClock  has only 0 sites available on device, but needs 1 sites.
	Term: ClkSys100MhzxC}}  -suppress 
set_msg_config  -ruleid {22}  -id {Place 30-475}  -string {{ERROR: [Place 30-475] IO terminal ClkSys100MhzxC with IOStandard LVCMOS18 is not placeable anywhere in the device.
Please check whether the IOSTANDARD is compatible with the target device.}}  -suppress 
set_msg_config  -ruleid {23}  -id {Place 30-374}  -string {{ERROR: [Place 30-374] IO placer failed to find a solution
Below is the partial placement that can be analyzed to see if any constraint modifications will make the IO placement problem easier to solve.
0. ClkSys100MhzxC

+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
|                                                                     IO Placement : Bank Stats                                                                           |
+----+-------+-------+------------------------------------------------------------------------+------------------------------------------+--------+--------+--------+-----+
| Id | Pins  | Terms |                               Standards                                |                IDelayCtrls               |  VREF  |  VCCO  |   VR   | DCI |
+----+-------+-------+------------------------------------------------------------------------+------------------------------------------+--------+--------+--------+-----+
|  0 |     0 |     0 |                                                                        |                                          |        |        |        |     |
| 13 |    35 |     0 |                                                                        |                                          |        |        |        |     |
| 14 |    50 |     0 |                                                                        |                                          |        |        |        |     |
| 15 |    50 |     0 |                                                                        |                                          |        |        |        |     |
| 16 |    50 |     1 | LVCMOS12(1)                                                            |                                          |        |  +1.20 |    YES |     |
| 34 |    50 |     9 | LVCMOS33(1)  TMDS_33(8)                                                |                                          |        |  +3.30 |    YES |     |
| 35 |    50 |     0 |                                                                        |                                          |        |        |        |     |
+----+-------+-------+------------------------------------------------------------------------+------------------------------------------+--------+--------+--------+-----+
|    |   285 |    10 |                                                                        |                                          |        |        |        |     |
+----+-------+-------+------------------------------------------------------------------------+------------------------------------------+--------+--------+--------+-----+

IO Placement:
+--------+----------------------+-----------------+----------------------+----------------------+----------------------+
| BankId |             Terminal | Standard        | Site                 | Pin                  | Attributes           |
+--------+----------------------+-----------------+----------------------+----------------------+----------------------+
| 16     | RstxR                | LVCMOS12        | IOB_X0Y209           | B22                  |                      |
+--------+----------------------+-----------------+----------------------+----------------------+----------------------+
| 34     | HdmiTxClkPxSO        | TMDS_33         | IOB_X1Y148           | T1                   |                      |
|        | HdmiTxClkNxSO        | TMDS_33         | IOB_X1Y147           | U1                   |                      |
|        | HdmiTxPxDO[0]        | TMDS_33         | IOB_X1Y140           | W1                   |                      |
|        | HdmiTxNxDO[0]        | TMDS_33         | IOB_X1Y139           | Y1                   |                      |
|        | HdmiTxPxDO[1]        | TMDS_33         | IOB_X1Y136           | AA1                  |                      |
|        | HdmiTxNxDO[1]        | TMDS_33         | IOB_X1Y135           | AB1                  |                      |
|        | HdmiTxPxDO[2]        | TMDS_33         | IOB_X1Y134           | AB3                  |                      |
|        | HdmiTxNxDO[2]        | TMDS_33         | IOB_X1Y133           | AB2                  |                      |
|        | HdmiTxRsclxSO        | LVCMOS33        | IOB_X1Y138           | U3                   |                      |
+--------+----------------------+-----------------+----------------------+----------------------+----------------------+}}  -suppress 
set_msg_config  -ruleid {24}  -id {Place 30-69}  -string {{ERROR: [Place 30-69] Instance HdmixI/ClkVgaHdmi1024x600xG.ClkHdmi1024x600xI/inst/clkin1_ibufg (IBUF driven by I/O terminal ClkSys100MhzxC) is unplaced after IO placer}}  -suppress 
set_msg_config  -ruleid {25}  -id {Place 30-602}  -string {{ERROR: [Place 30-602] IO port 'ClkSys100MhzxC' is driving multiple buffers. This will lead to unplaceable/unroutable situation.
The buffers connected are:
    HdmixI/ClkVgaHdmi1024x600xG.ClkHdmi1024x600xI/inst/clkin1_ibufg {IBUF}
    HdmixI/ClkVgaHdmi1024x600xG.ClkVga1024x600xI/inst/clkin1_ibufg {IBUF}}}  -suppress 
set_msg_config  -ruleid {26}  -id {Place 30-99}  -string {{ERROR: [Place 30-99] Placer failed with error: 'Implementation Feasibility check failed, Please see the previously displayed individual error or warning messages for more details.'
Please review all ERROR, CRITICAL WARNING, and WARNING messages during placement to understand the cause for failure.}}  -suppress 
set_msg_config  -ruleid {27}  -id {Common 17-69}  -string {{ERROR: [Common 17-69] Command failed: Placer could not place all instances}}  -suppress 
set_msg_config  -ruleid {28}  -id {Synth 8-3331}  -string {{WARNING: [Synth 8-3331] design mse_mandelbrot has unconnected port HdmiTxHpdxSI}}  -suppress 
set_msg_config  -ruleid {29}  -id {Synth 8-3332}  -string {{WARNING: [Synth 8-3332] Sequential element (ImageGeneratorxI/DataxD_reg[19]) is unused and will be removed from module mse_mandelbrot.}}  -suppress 
set_msg_config  -ruleid {30}  -id {DRC REQP-1839}  -string {{WARNING: [DRC REQP-1839] RAMB36 async control check: The RAMB36E1 BramVideoMemory1024x768x9xI/U0/inst_blk_mem_gen/gnbram.gnativebmg.native_blk_mem_gen/valid.cstr/ramloop[0].ram.r/prim_noinit.ram/DEVICE_7SERIES.NO_BMM_INFO.TRUE_DP.SIMPLE_PRIM36.ram has an input control pin BramVideoMemory1024x768x9xI/U0/inst_blk_mem_gen/gnbram.gnativebmg.native_blk_mem_gen/valid.cstr/ramloop[0].ram.r/prim_noinit.ram/DEVICE_7SERIES.NO_BMM_INFO.TRUE_DP.SIMPLE_PRIM36.ram/ADDRARDADDR[10] (net: BramVideoMemory1024x768x9xI/U0/inst_blk_mem_gen/gnbram.gnativebmg.native_blk_mem_gen/valid.cstr/ramloop[0].ram.r/prim_noinit.ram/addra[7]) which is driven by a register (HdmixI/VgaxI/VgaControlerxI/VidOnxS_reg) that has an active asychronous set or reset. This may cause corruption of the memory contents and/or read values when the set/reset is asserted and is not analyzed by the default static timing analysis. It is suggested to eliminate the use of a set/reset to registers driving this RAMB pin or else use a synchronous reset in which the assertion of the reset is timed by default.}}  -suppress 
set_msg_config  -ruleid {31}  -id {Place 30-58}  -string {{ERROR: [Place 30-58] IO placement is infeasible. Number of unplaced terminals (1) is greater than number of available sites (0).
The following are banks with available pins: 
 IO Group: 0 with : SioStd: LVCMOS18   VCCO = 1.8 Termination: 0  TermDir:  In   RangeId: 1  has only 0 sites available on device, but needs 1 sites.
	Term: ClkSys100MhzxC}}  -suppress 
set_msg_config  -ruleid {32}  -id {Place 30-69}  -string {{ERROR: [Place 30-69] Instance HdmixI/ClkVgaHdmi1024x600xG.ClkVga1024x600xI/inst/clkin1_ibufg (IBUF driven by I/O terminal ClkSys100MhzxC) is unplaced after IO placer}}  -suppress 
set_msg_config  -ruleid {33}  -id {Synth 8-3332}  -string {{WARNING: [Synth 8-3332] Sequential element (ImageGeneratorxI/DataxD_reg[18]) is unused and will be removed from module mse_mandelbrot.}}  -suppress 
set_msg_config  -ruleid {34}  -id {DRC REQP-1839}  -string {{WARNING: [DRC REQP-1839] RAMB36 async control check: The RAMB36E1 BramVideoMemory1024x768x9xI/U0/inst_blk_mem_gen/gnbram.gnativebmg.native_blk_mem_gen/valid.cstr/ramloop[0].ram.r/prim_noinit.ram/DEVICE_7SERIES.NO_BMM_INFO.TRUE_DP.SIMPLE_PRIM36.ram has an input control pin BramVideoMemory1024x768x9xI/U0/inst_blk_mem_gen/gnbram.gnativebmg.native_blk_mem_gen/valid.cstr/ramloop[0].ram.r/prim_noinit.ram/DEVICE_7SERIES.NO_BMM_INFO.TRUE_DP.SIMPLE_PRIM36.ram/ADDRARDADDR[11] (net: BramVideoMemory1024x768x9xI/U0/inst_blk_mem_gen/gnbram.gnativebmg.native_blk_mem_gen/valid.cstr/ramloop[0].ram.r/prim_noinit.ram/addra[8]) which is driven by a register (HdmixI/VgaxI/VgaControlerxI/HCountxD_reg[8]) that has an active asychronous set or reset. This may cause corruption of the memory contents and/or read values when the set/reset is asserted and is not analyzed by the default static timing analysis. It is suggested to eliminate the use of a set/reset to registers driving this RAMB pin or else use a synchronous reset in which the assertion of the reset is timed by default.}}  -suppress 
set_msg_config  -ruleid {35}  -id {Synth 8-3332}  -string {{WARNING: [Synth 8-3332] Sequential element (ImageGeneratorxI/DataxD_reg[17]) is unused and will be removed from module mse_mandelbrot.}}  -suppress 
set_msg_config  -ruleid {36}  -id {DRC REQP-1839}  -string {{WARNING: [DRC REQP-1839] RAMB36 async control check: The RAMB36E1 BramVideoMemory1024x768x9xI/U0/inst_blk_mem_gen/gnbram.gnativebmg.native_blk_mem_gen/valid.cstr/ramloop[0].ram.r/prim_noinit.ram/DEVICE_7SERIES.NO_BMM_INFO.TRUE_DP.SIMPLE_PRIM36.ram has an input control pin BramVideoMemory1024x768x9xI/U0/inst_blk_mem_gen/gnbram.gnativebmg.native_blk_mem_gen/valid.cstr/ramloop[0].ram.r/prim_noinit.ram/DEVICE_7SERIES.NO_BMM_INFO.TRUE_DP.SIMPLE_PRIM36.ram/ADDRARDADDR[11] (net: BramVideoMemory1024x768x9xI/U0/inst_blk_mem_gen/gnbram.gnativebmg.native_blk_mem_gen/valid.cstr/ramloop[0].ram.r/prim_noinit.ram/addra[8]) which is driven by a register (HdmixI/VgaxI/VgaControlerxI/VidOnxS_reg) that has an active asychronous set or reset. This may cause corruption of the memory contents and/or read values when the set/reset is asserted and is not analyzed by the default static timing analysis. It is suggested to eliminate the use of a set/reset to registers driving this RAMB pin or else use a synchronous reset in which the assertion of the reset is timed by default.}}  -suppress 
set_msg_config  -ruleid {37}  -id {Synth 8-3332}  -string {{WARNING: [Synth 8-3332] Sequential element (ImageGeneratorxI/DataxD_reg[16]) is unused and will be removed from module mse_mandelbrot.}}  -suppress 
set_msg_config  -ruleid {38}  -id {DRC REQP-1839}  -string {{WARNING: [DRC REQP-1839] RAMB36 async control check: The RAMB36E1 BramVideoMemory1024x768x9xI/U0/inst_blk_mem_gen/gnbram.gnativebmg.native_blk_mem_gen/valid.cstr/ramloop[0].ram.r/prim_noinit.ram/DEVICE_7SERIES.NO_BMM_INFO.TRUE_DP.SIMPLE_PRIM36.ram has an input control pin BramVideoMemory1024x768x9xI/U0/inst_blk_mem_gen/gnbram.gnativebmg.native_blk_mem_gen/valid.cstr/ramloop[0].ram.r/prim_noinit.ram/DEVICE_7SERIES.NO_BMM_INFO.TRUE_DP.SIMPLE_PRIM36.ram/ADDRARDADDR[12] (net: BramVideoMemory1024x768x9xI/U0/inst_blk_mem_gen/gnbram.gnativebmg.native_blk_mem_gen/valid.cstr/ramloop[0].ram.r/prim_noinit.ram/addra[9]) which is driven by a register (HdmixI/VgaxI/VgaControlerxI/HCountxD_reg[9]) that has an active asychronous set or reset. This may cause corruption of the memory contents and/or read values when the set/reset is asserted and is not analyzed by the default static timing analysis. It is suggested to eliminate the use of a set/reset to registers driving this RAMB pin or else use a synchronous reset in which the assertion of the reset is timed by default.}}  -suppress 
set_msg_config  -ruleid {39}  -id {Labtools 27-2269}  -string {{ERROR: [Labtools 27-2269] No devices detected on target localhost:3121/xilinx_tcf/Digilent/210276724168.
Check cable connectivity and that the target board is powered up then
use the disconnect_hw_server and connect_hw_server to re-register this hardware target.}}  -suppress 
set_msg_config  -ruleid {4}  -id {Common 17-165}  -string {{ERROR: [Common 17-165] Too many positional options when parsing 'out', please type '::xit::add_dynamic_port -help' for usage info.}}  -suppress 
set_msg_config  -ruleid {40}  -id {Labtools 27-3361}  -string {{WARNING: [Labtools 27-3361] The debug hub core was not detected.
Resolution: 
1. Make sure the clock connected to the debug hub (dbg_hub) core is a free running clock and is active.
2. Make sure the BSCAN_SWITCH_USER_MASK device property in Vivado Hardware Manager reflects the user scan chain setting in the design and refresh the device.  To determine the user scan chain setting in the design, open the implemented design and use 'get_property C_USER_SCAN_CHAIN [get_debug_cores dbg_hub]'.
For more details on setting the scan chain property, consult the Vivado Debug and Programming User Guide (UG908).}}  -suppress 
set_msg_config  -ruleid {41}  -id {Synth 8-3332}  -string {{WARNING: [Synth 8-3332] Sequential element (ImageGeneratorxI/DataxD_reg[12]) is unused and will be removed from module mse_mandelbrot.}}  -suppress 
set_msg_config  -ruleid {42}  -id {Synth 8-3332}  -string {{WARNING: [Synth 8-3332] Sequential element (ImageGeneratorxI/DataxD_reg[11]) is unused and will be removed from module mse_mandelbrot.}}  -suppress 
set_msg_config  -ruleid {43}  -id {Synth 8-3332}  -string {{WARNING: [Synth 8-3332] Sequential element (ImageGeneratorxI/DataxD_reg[10]) is unused and will be removed from module mse_mandelbrot.}}  -suppress 
set_msg_config  -ruleid {44}  -id {Synth 8-3332}  -string {{WARNING: [Synth 8-3332] Sequential element (ImageGeneratorxI/DataxD_reg[9]) is unused and will be removed from module mse_mandelbrot.}}  -suppress 
set_msg_config  -ruleid {45}  -id {Synth 8-3332}  -string {{WARNING: [Synth 8-3332] Sequential element (ImageGeneratorxI/DataxD_reg[8]) is unused and will be removed from module mse_mandelbrot.}}  -suppress 
set_msg_config  -ruleid {46}  -id {Synth 8-3332}  -string {{WARNING: [Synth 8-3332] Sequential element (ImageGeneratorxI/DataxD_reg[4]) is unused and will be removed from module mse_mandelbrot.}}  -suppress 
set_msg_config  -ruleid {47}  -id {Synth 8-3332}  -string {{WARNING: [Synth 8-3332] Sequential element (ImageGeneratorxI/DataxD_reg[3]) is unused and will be removed from module mse_mandelbrot.}}  -suppress 
set_msg_config  -ruleid {48}  -id {Synth 8-3332}  -string {{WARNING: [Synth 8-3332] Sequential element (ImageGeneratorxI/DataxD_reg[2]) is unused and will be removed from module mse_mandelbrot.}}  -suppress 
set_msg_config  -ruleid {49}  -id {Synth 8-3332}  -string {{WARNING: [Synth 8-3332] Sequential element (ImageGeneratorxI/DataxD_reg[1]) is unused and will be removed from module mse_mandelbrot.}}  -suppress 
set_msg_config  -ruleid {5}  -id {IP_Flow 19-1747}  -string {{CRITICAL WARNING: [IP_Flow 19-1747] Failed to deliver file '/opt/Xilinx/Vivado/2017.4/data/ip/xilinx/clk_wiz_v5_4/elaborate/ports.xit': ERROR: [Common 17-165] Too many positional options when parsing 'out', please type '::xit::add_dynamic_port -help' for usage info.}}  -suppress 
set_msg_config  -ruleid {50}  -id {Synth 8-3332}  -string {{WARNING: [Synth 8-3332] Sequential element (ImageGeneratorxI/DataxD_reg[0]) is unused and will be removed from module mse_mandelbrot.}}  -suppress 
set_msg_config  -ruleid {51}  -id {Synth 8-3332}  -string {{WARNING: [Synth 8-3332] Sequential element (HdmixI/VgaToHdmixI/TmdsEncoderC2xI/TmdsEncodedDataxDO_reg[8]) is unused and will be removed from module mse_mandelbrot.}}  -suppress 
set_msg_config  -ruleid {52}  -id {DRC REQP-1839}  -string {{WARNING: [DRC REQP-1839] RAMB36 async control check: The RAMB36E1 BramVideoMemory1024x768x9xI/U0/inst_blk_mem_gen/gnbram.gnativebmg.native_blk_mem_gen/valid.cstr/ramloop[0].ram.r/prim_noinit.ram/DEVICE_7SERIES.NO_BMM_INFO.TRUE_DP.SIMPLE_PRIM36.ram has an input control pin BramVideoMemory1024x768x9xI/U0/inst_blk_mem_gen/gnbram.gnativebmg.native_blk_mem_gen/valid.cstr/ramloop[0].ram.r/prim_noinit.ram/DEVICE_7SERIES.NO_BMM_INFO.TRUE_DP.SIMPLE_PRIM36.ram/ADDRARDADDR[12] (net: BramVideoMemory1024x768x9xI/U0/inst_blk_mem_gen/gnbram.gnativebmg.native_blk_mem_gen/valid.cstr/ramloop[0].ram.r/prim_noinit.ram/addra[9]) which is driven by a register (HdmixI/VgaxI/VgaControlerxI/VidOnxS_reg) that has an active asychronous set or reset. This may cause corruption of the memory contents and/or read values when the set/reset is asserted and is not analyzed by the default static timing analysis. It is suggested to eliminate the use of a set/reset to registers driving this RAMB pin or else use a synchronous reset in which the assertion of the reset is timed by default.}}  -suppress 
set_msg_config  -ruleid {53}  -id {DRC REQP-1839}  -string {{WARNING: [DRC REQP-1839] RAMB36 async control check: The RAMB36E1 BramVideoMemory1024x768x9xI/U0/inst_blk_mem_gen/gnbram.gnativebmg.native_blk_mem_gen/valid.cstr/ramloop[0].ram.r/prim_noinit.ram/DEVICE_7SERIES.NO_BMM_INFO.TRUE_DP.SIMPLE_PRIM36.ram has an input control pin BramVideoMemory1024x768x9xI/U0/inst_blk_mem_gen/gnbram.gnativebmg.native_blk_mem_gen/valid.cstr/ramloop[0].ram.r/prim_noinit.ram/DEVICE_7SERIES.NO_BMM_INFO.TRUE_DP.SIMPLE_PRIM36.ram/ADDRARDADDR[13] (net: BramVideoMemory1024x768x9xI/U0/inst_blk_mem_gen/gnbram.gnativebmg.native_blk_mem_gen/valid.cstr/ramloop[0].ram.r/prim_noinit.ram/addra[10]) which is driven by a register (HdmixI/VgaxI/VgaControlerxI/VCountxD_reg[0]) that has an active asychronous set or reset. This may cause corruption of the memory contents and/or read values when the set/reset is asserted and is not analyzed by the default static timing analysis. It is suggested to eliminate the use of a set/reset to registers driving this RAMB pin or else use a synchronous reset in which the assertion of the reset is timed by default.}}  -suppress 
set_msg_config  -ruleid {54}  -id {DRC REQP-1839}  -string {{WARNING: [DRC REQP-1839] RAMB36 async control check: The RAMB36E1 BramVideoMemory1024x768x9xI/U0/inst_blk_mem_gen/gnbram.gnativebmg.native_blk_mem_gen/valid.cstr/ramloop[0].ram.r/prim_noinit.ram/DEVICE_7SERIES.NO_BMM_INFO.TRUE_DP.SIMPLE_PRIM36.ram has an input control pin BramVideoMemory1024x768x9xI/U0/inst_blk_mem_gen/gnbram.gnativebmg.native_blk_mem_gen/valid.cstr/ramloop[0].ram.r/prim_noinit.ram/DEVICE_7SERIES.NO_BMM_INFO.TRUE_DP.SIMPLE_PRIM36.ram/ADDRARDADDR[14] (net: BramVideoMemory1024x768x9xI/U0/inst_blk_mem_gen/gnbram.gnativebmg.native_blk_mem_gen/valid.cstr/ramloop[0].ram.r/prim_noinit.ram/addra[11]) which is driven by a register (HdmixI/VgaxI/VgaControlerxI/VCountxD_reg[1]) that has an active asychronous set or reset. This may cause corruption of the memory contents and/or read values when the set/reset is asserted and is not analyzed by the default static timing analysis. It is suggested to eliminate the use of a set/reset to registers driving this RAMB pin or else use a synchronous reset in which the assertion of the reset is timed by default.}}  -suppress 
set_msg_config  -ruleid {55}  -id {DRC REQP-1839}  -string {{WARNING: [DRC REQP-1839] RAMB36 async control check: The RAMB36E1 BramVideoMemory1024x768x9xI/U0/inst_blk_mem_gen/gnbram.gnativebmg.native_blk_mem_gen/valid.cstr/ramloop[0].ram.r/prim_noinit.ram/DEVICE_7SERIES.NO_BMM_INFO.TRUE_DP.SIMPLE_PRIM36.ram has an input control pin BramVideoMemory1024x768x9xI/U0/inst_blk_mem_gen/gnbram.gnativebmg.native_blk_mem_gen/valid.cstr/ramloop[0].ram.r/prim_noinit.ram/DEVICE_7SERIES.NO_BMM_INFO.TRUE_DP.SIMPLE_PRIM36.ram/ADDRARDADDR[4] (net: BramVideoMemory1024x768x9xI/U0/inst_blk_mem_gen/gnbram.gnativebmg.native_blk_mem_gen/valid.cstr/ramloop[0].ram.r/prim_noinit.ram/addra[1]) which is driven by a register (HdmixI/VgaxI/VgaControlerxI/HCountxD_reg[1]) that has an active asychronous set or reset. This may cause corruption of the memory contents and/or read values when the set/reset is asserted and is not analyzed by the default static timing analysis. It is suggested to eliminate the use of a set/reset to registers driving this RAMB pin or else use a synchronous reset in which the assertion of the reset is timed by default.}}  -suppress 
set_msg_config  -ruleid {56}  -id {DRC REQP-1839}  -string {{WARNING: [DRC REQP-1839] RAMB36 async control check: The RAMB36E1 BramVideoMemory1024x768x9xI/U0/inst_blk_mem_gen/gnbram.gnativebmg.native_blk_mem_gen/valid.cstr/ramloop[0].ram.r/prim_noinit.ram/DEVICE_7SERIES.NO_BMM_INFO.TRUE_DP.SIMPLE_PRIM36.ram has an input control pin BramVideoMemory1024x768x9xI/U0/inst_blk_mem_gen/gnbram.gnativebmg.native_blk_mem_gen/valid.cstr/ramloop[0].ram.r/prim_noinit.ram/DEVICE_7SERIES.NO_BMM_INFO.TRUE_DP.SIMPLE_PRIM36.ram/ADDRARDADDR[4] (net: BramVideoMemory1024x768x9xI/U0/inst_blk_mem_gen/gnbram.gnativebmg.native_blk_mem_gen/valid.cstr/ramloop[0].ram.r/prim_noinit.ram/addra[1]) which is driven by a register (HdmixI/VgaxI/VgaControlerxI/VidOnxS_reg) that has an active asychronous set or reset. This may cause corruption of the memory contents and/or read values when the set/reset is asserted and is not analyzed by the default static timing analysis. It is suggested to eliminate the use of a set/reset to registers driving this RAMB pin or else use a synchronous reset in which the assertion of the reset is timed by default.}}  -suppress 
set_msg_config  -ruleid {57}  -id {DRC REQP-1839}  -string {{WARNING: [DRC REQP-1839] RAMB36 async control check: The RAMB36E1 BramVideoMemory1024x768x9xI/U0/inst_blk_mem_gen/gnbram.gnativebmg.native_blk_mem_gen/valid.cstr/ramloop[0].ram.r/prim_noinit.ram/DEVICE_7SERIES.NO_BMM_INFO.TRUE_DP.SIMPLE_PRIM36.ram has an input control pin BramVideoMemory1024x768x9xI/U0/inst_blk_mem_gen/gnbram.gnativebmg.native_blk_mem_gen/valid.cstr/ramloop[0].ram.r/prim_noinit.ram/DEVICE_7SERIES.NO_BMM_INFO.TRUE_DP.SIMPLE_PRIM36.ram/ADDRARDADDR[5] (net: BramVideoMemory1024x768x9xI/U0/inst_blk_mem_gen/gnbram.gnativebmg.native_blk_mem_gen/valid.cstr/ramloop[0].ram.r/prim_noinit.ram/addra[2]) which is driven by a register (HdmixI/VgaxI/VgaControlerxI/HCountxD_reg[2]) that has an active asychronous set or reset. This may cause corruption of the memory contents and/or read values when the set/reset is asserted and is not analyzed by the default static timing analysis. It is suggested to eliminate the use of a set/reset to registers driving this RAMB pin or else use a synchronous reset in which the assertion of the reset is timed by default.}}  -suppress 
set_msg_config  -ruleid {58}  -id {DRC REQP-1839}  -string {{WARNING: [DRC REQP-1839] RAMB36 async control check: The RAMB36E1 BramVideoMemory1024x768x9xI/U0/inst_blk_mem_gen/gnbram.gnativebmg.native_blk_mem_gen/valid.cstr/ramloop[0].ram.r/prim_noinit.ram/DEVICE_7SERIES.NO_BMM_INFO.TRUE_DP.SIMPLE_PRIM36.ram has an input control pin BramVideoMemory1024x768x9xI/U0/inst_blk_mem_gen/gnbram.gnativebmg.native_blk_mem_gen/valid.cstr/ramloop[0].ram.r/prim_noinit.ram/DEVICE_7SERIES.NO_BMM_INFO.TRUE_DP.SIMPLE_PRIM36.ram/ADDRARDADDR[5] (net: BramVideoMemory1024x768x9xI/U0/inst_blk_mem_gen/gnbram.gnativebmg.native_blk_mem_gen/valid.cstr/ramloop[0].ram.r/prim_noinit.ram/addra[2]) which is driven by a register (HdmixI/VgaxI/VgaControlerxI/VidOnxS_reg) that has an active asychronous set or reset. This may cause corruption of the memory contents and/or read values when the set/reset is asserted and is not analyzed by the default static timing analysis. It is suggested to eliminate the use of a set/reset to registers driving this RAMB pin or else use a synchronous reset in which the assertion of the reset is timed by default.}}  -suppress 
set_msg_config  -ruleid {59}  -id {DRC REQP-1839}  -string {{WARNING: [DRC REQP-1839] RAMB36 async control check: The RAMB36E1 BramVideoMemory1024x768x9xI/U0/inst_blk_mem_gen/gnbram.gnativebmg.native_blk_mem_gen/valid.cstr/ramloop[0].ram.r/prim_noinit.ram/DEVICE_7SERIES.NO_BMM_INFO.TRUE_DP.SIMPLE_PRIM36.ram has an input control pin BramVideoMemory1024x768x9xI/U0/inst_blk_mem_gen/gnbram.gnativebmg.native_blk_mem_gen/valid.cstr/ramloop[0].ram.r/prim_noinit.ram/DEVICE_7SERIES.NO_BMM_INFO.TRUE_DP.SIMPLE_PRIM36.ram/ADDRARDADDR[6] (net: BramVideoMemory1024x768x9xI/U0/inst_blk_mem_gen/gnbram.gnativebmg.native_blk_mem_gen/valid.cstr/ramloop[0].ram.r/prim_noinit.ram/addra[3]) which is driven by a register (HdmixI/VgaxI/VgaControlerxI/HCountxD_reg[3]) that has an active asychronous set or reset. This may cause corruption of the memory contents and/or read values when the set/reset is asserted and is not analyzed by the default static timing analysis. It is suggested to eliminate the use of a set/reset to registers driving this RAMB pin or else use a synchronous reset in which the assertion of the reset is timed by default.}}  -suppress 
set_msg_config  -ruleid {6}  -id {IP_Flow 19-167}  -string {{ERROR: [IP_Flow 19-167] Failed to deliver one or more file(s).}}  -suppress 
set_msg_config  -ruleid {60}  -id {DRC REQP-1839}  -string {{WARNING: [DRC REQP-1839] RAMB36 async control check: The RAMB36E1 BramVideoMemory1024x768x9xI/U0/inst_blk_mem_gen/gnbram.gnativebmg.native_blk_mem_gen/valid.cstr/ramloop[0].ram.r/prim_noinit.ram/DEVICE_7SERIES.NO_BMM_INFO.TRUE_DP.SIMPLE_PRIM36.ram has an input control pin BramVideoMemory1024x768x9xI/U0/inst_blk_mem_gen/gnbram.gnativebmg.native_blk_mem_gen/valid.cstr/ramloop[0].ram.r/prim_noinit.ram/DEVICE_7SERIES.NO_BMM_INFO.TRUE_DP.SIMPLE_PRIM36.ram/ADDRARDADDR[6] (net: BramVideoMemory1024x768x9xI/U0/inst_blk_mem_gen/gnbram.gnativebmg.native_blk_mem_gen/valid.cstr/ramloop[0].ram.r/prim_noinit.ram/addra[3]) which is driven by a register (HdmixI/VgaxI/VgaControlerxI/VidOnxS_reg) that has an active asychronous set or reset. This may cause corruption of the memory contents and/or read values when the set/reset is asserted and is not analyzed by the default static timing analysis. It is suggested to eliminate the use of a set/reset to registers driving this RAMB pin or else use a synchronous reset in which the assertion of the reset is timed by default.}}  -suppress 
set_msg_config  -ruleid {61}  -id {DRC REQP-1839}  -string {{WARNING: [DRC REQP-1839] RAMB36 async control check: The RAMB36E1 BramVideoMemory1024x768x9xI/U0/inst_blk_mem_gen/gnbram.gnativebmg.native_blk_mem_gen/valid.cstr/ramloop[0].ram.r/prim_noinit.ram/DEVICE_7SERIES.NO_BMM_INFO.TRUE_DP.SIMPLE_PRIM36.ram has an input control pin BramVideoMemory1024x768x9xI/U0/inst_blk_mem_gen/gnbram.gnativebmg.native_blk_mem_gen/valid.cstr/ramloop[0].ram.r/prim_noinit.ram/DEVICE_7SERIES.NO_BMM_INFO.TRUE_DP.SIMPLE_PRIM36.ram/ADDRARDADDR[7] (net: BramVideoMemory1024x768x9xI/U0/inst_blk_mem_gen/gnbram.gnativebmg.native_blk_mem_gen/valid.cstr/ramloop[0].ram.r/prim_noinit.ram/addra[4]) which is driven by a register (HdmixI/VgaxI/VgaControlerxI/HCountxD_reg[4]) that has an active asychronous set or reset. This may cause corruption of the memory contents and/or read values when the set/reset is asserted and is not analyzed by the default static timing analysis. It is suggested to eliminate the use of a set/reset to registers driving this RAMB pin or else use a synchronous reset in which the assertion of the reset is timed by default.}}  -suppress 
set_msg_config  -ruleid {62}  -id {DRC REQP-1839}  -string {{WARNING: [DRC REQP-1839] RAMB36 async control check: The RAMB36E1 BramVideoMemory1024x768x9xI/U0/inst_blk_mem_gen/gnbram.gnativebmg.native_blk_mem_gen/valid.cstr/ramloop[0].ram.r/prim_noinit.ram/DEVICE_7SERIES.NO_BMM_INFO.TRUE_DP.SIMPLE_PRIM36.ram has an input control pin BramVideoMemory1024x768x9xI/U0/inst_blk_mem_gen/gnbram.gnativebmg.native_blk_mem_gen/valid.cstr/ramloop[0].ram.r/prim_noinit.ram/DEVICE_7SERIES.NO_BMM_INFO.TRUE_DP.SIMPLE_PRIM36.ram/ADDRARDADDR[7] (net: BramVideoMemory1024x768x9xI/U0/inst_blk_mem_gen/gnbram.gnativebmg.native_blk_mem_gen/valid.cstr/ramloop[0].ram.r/prim_noinit.ram/addra[4]) which is driven by a register (HdmixI/VgaxI/VgaControlerxI/VidOnxS_reg) that has an active asychronous set or reset. This may cause corruption of the memory contents and/or read values when the set/reset is asserted and is not analyzed by the default static timing analysis. It is suggested to eliminate the use of a set/reset to registers driving this RAMB pin or else use a synchronous reset in which the assertion of the reset is timed by default.}}  -suppress 
set_msg_config  -ruleid {63}  -id {DRC REQP-1839}  -string {{WARNING: [DRC REQP-1839] RAMB36 async control check: The RAMB36E1 BramVideoMemory1024x768x9xI/U0/inst_blk_mem_gen/gnbram.gnativebmg.native_blk_mem_gen/valid.cstr/ramloop[0].ram.r/prim_noinit.ram/DEVICE_7SERIES.NO_BMM_INFO.TRUE_DP.SIMPLE_PRIM36.ram has an input control pin BramVideoMemory1024x768x9xI/U0/inst_blk_mem_gen/gnbram.gnativebmg.native_blk_mem_gen/valid.cstr/ramloop[0].ram.r/prim_noinit.ram/DEVICE_7SERIES.NO_BMM_INFO.TRUE_DP.SIMPLE_PRIM36.ram/ADDRARDADDR[8] (net: BramVideoMemory1024x768x9xI/U0/inst_blk_mem_gen/gnbram.gnativebmg.native_blk_mem_gen/valid.cstr/ramloop[0].ram.r/prim_noinit.ram/addra[5]) which is driven by a register (HdmixI/VgaxI/VgaControlerxI/HCountxD_reg[5]) that has an active asychronous set or reset. This may cause corruption of the memory contents and/or read values when the set/reset is asserted and is not analyzed by the default static timing analysis. It is suggested to eliminate the use of a set/reset to registers driving this RAMB pin or else use a synchronous reset in which the assertion of the reset is timed by default.}}  -suppress 
set_msg_config  -ruleid {64}  -id {DRC REQP-1839}  -string {{WARNING: [DRC REQP-1839] RAMB36 async control check: The RAMB36E1 BramVideoMemory1024x768x9xI/U0/inst_blk_mem_gen/gnbram.gnativebmg.native_blk_mem_gen/valid.cstr/ramloop[0].ram.r/prim_noinit.ram/DEVICE_7SERIES.NO_BMM_INFO.TRUE_DP.SIMPLE_PRIM36.ram has an input control pin BramVideoMemory1024x768x9xI/U0/inst_blk_mem_gen/gnbram.gnativebmg.native_blk_mem_gen/valid.cstr/ramloop[0].ram.r/prim_noinit.ram/DEVICE_7SERIES.NO_BMM_INFO.TRUE_DP.SIMPLE_PRIM36.ram/ADDRARDADDR[8] (net: BramVideoMemory1024x768x9xI/U0/inst_blk_mem_gen/gnbram.gnativebmg.native_blk_mem_gen/valid.cstr/ramloop[0].ram.r/prim_noinit.ram/addra[5]) which is driven by a register (HdmixI/VgaxI/VgaControlerxI/VidOnxS_reg) that has an active asychronous set or reset. This may cause corruption of the memory contents and/or read values when the set/reset is asserted and is not analyzed by the default static timing analysis. It is suggested to eliminate the use of a set/reset to registers driving this RAMB pin or else use a synchronous reset in which the assertion of the reset is timed by default.}}  -suppress 
set_msg_config  -ruleid {65}  -id {DRC REQP-1839}  -string {{WARNING: [DRC REQP-1839] RAMB36 async control check: The RAMB36E1 BramVideoMemory1024x768x9xI/U0/inst_blk_mem_gen/gnbram.gnativebmg.native_blk_mem_gen/valid.cstr/ramloop[0].ram.r/prim_noinit.ram/DEVICE_7SERIES.NO_BMM_INFO.TRUE_DP.SIMPLE_PRIM36.ram has an input control pin BramVideoMemory1024x768x9xI/U0/inst_blk_mem_gen/gnbram.gnativebmg.native_blk_mem_gen/valid.cstr/ramloop[0].ram.r/prim_noinit.ram/DEVICE_7SERIES.NO_BMM_INFO.TRUE_DP.SIMPLE_PRIM36.ram/ADDRARDADDR[9] (net: BramVideoMemory1024x768x9xI/U0/inst_blk_mem_gen/gnbram.gnativebmg.native_blk_mem_gen/valid.cstr/ramloop[0].ram.r/prim_noinit.ram/addra[6]) which is driven by a register (HdmixI/VgaxI/VgaControlerxI/HCountxD_reg[6]) that has an active asychronous set or reset. This may cause corruption of the memory contents and/or read values when the set/reset is asserted and is not analyzed by the default static timing analysis. It is suggested to eliminate the use of a set/reset to registers driving this RAMB pin or else use a synchronous reset in which the assertion of the reset is timed by default.}}  -suppress 
set_msg_config  -ruleid {66}  -id {DRC REQP-1839}  -string {{WARNING: [DRC REQP-1839] RAMB36 async control check: The RAMB36E1 BramVideoMemory1024x768x9xI/U0/inst_blk_mem_gen/gnbram.gnativebmg.native_blk_mem_gen/valid.cstr/ramloop[0].ram.r/prim_noinit.ram/DEVICE_7SERIES.NO_BMM_INFO.TRUE_DP.SIMPLE_PRIM36.ram has an input control pin BramVideoMemory1024x768x9xI/U0/inst_blk_mem_gen/gnbram.gnativebmg.native_blk_mem_gen/valid.cstr/ramloop[0].ram.r/prim_noinit.ram/DEVICE_7SERIES.NO_BMM_INFO.TRUE_DP.SIMPLE_PRIM36.ram/ADDRARDADDR[9] (net: BramVideoMemory1024x768x9xI/U0/inst_blk_mem_gen/gnbram.gnativebmg.native_blk_mem_gen/valid.cstr/ramloop[0].ram.r/prim_noinit.ram/addra[6]) which is driven by a register (HdmixI/VgaxI/VgaControlerxI/VidOnxS_reg) that has an active asychronous set or reset. This may cause corruption of the memory contents and/or read values when the set/reset is asserted and is not analyzed by the default static timing analysis. It is suggested to eliminate the use of a set/reset to registers driving this RAMB pin or else use a synchronous reset in which the assertion of the reset is timed by default.}}  -suppress 
set_msg_config  -ruleid {7}  -id {IP_Flow 19-3541}  -string {{ERROR: [IP_Flow 19-3541] IP Elaboration error: Failed to generate IP 'clk_wiz_0'. Failed to generate 'Elaborate Ports' outputs:}}  -suppress 
set_msg_config  -ruleid {8}  -id {Vivado 12-3523}  -string {{WARNING: [Vivado 12-3523] Attempt to change 'Component_Name' from 'clk_vga_1024x600' to 'clk_vga_1024x600' is not allowed and is ignored.}}  -suppress 
set_msg_config  -ruleid {9}  -id {Vivado 12-3523}  -string {{WARNING: [Vivado 12-3523] Attempt to change 'Component_Name' from 'clk_hdmi_1024x600' to 'clk_hdmi_1024x600' is not allowed and is ignored.}}  -suppress 
set_param project.vivado.isBlockSynthRun true
set_msg_config -msgmgr_mode ooc_run
create_project -in_memory -part xc7a200tsbg484-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir /home/joco/Documents/cours/FPGA/master/nexys_video/mse_mandelbrot/mse_mandelbrot.cache/wt [current_project]
set_property parent.project_path /home/joco/Documents/cours/FPGA/master/nexys_video/mse_mandelbrot/mse_mandelbrot.xpr [current_project]
set_property XPM_LIBRARIES {XPM_CDC XPM_MEMORY} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language VHDL [current_project]
set_property ip_output_repo /home/joco/Documents/cours/FPGA/master/nexys_video/mse_mandelbrot/mse_mandelbrot.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_ip -quiet /home/joco/Documents/cours/FPGA/master/nexys_video/mse_mandelbrot/mse_mandelbrot.srcs/sources_1/ip/clk_hdmi_640x480/clk_hdmi_640x480.xci
set_property used_in_implementation false [get_files -all /home/joco/Documents/cours/FPGA/master/nexys_video/mse_mandelbrot/mse_mandelbrot.srcs/sources_1/ip/clk_hdmi_640x480/clk_hdmi_640x480_board.xdc]
set_property used_in_implementation false [get_files -all /home/joco/Documents/cours/FPGA/master/nexys_video/mse_mandelbrot/mse_mandelbrot.srcs/sources_1/ip/clk_hdmi_640x480/clk_hdmi_640x480.xdc]
set_property used_in_implementation false [get_files -all /home/joco/Documents/cours/FPGA/master/nexys_video/mse_mandelbrot/mse_mandelbrot.srcs/sources_1/ip/clk_hdmi_640x480/clk_hdmi_640x480_ooc.xdc]

# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]

set cached_ip [config_ip_cache -export -no_bom -use_project_ipc -dir /home/joco/Documents/cours/FPGA/master/nexys_video/mse_mandelbrot/mse_mandelbrot.runs/clk_hdmi_640x480_synth_1 -new_name clk_hdmi_640x480 -ip [get_ips clk_hdmi_640x480]]

if { $cached_ip eq {} } {

synth_design -top clk_hdmi_640x480 -part xc7a200tsbg484-1 -mode out_of_context

#---------------------------------------------------------
# Generate Checkpoint/Stub/Simulation Files For IP Cache
#---------------------------------------------------------
# disable binary constraint mode for IPCache checkpoints
set_param constraints.enableBinaryConstraints false

catch {
 write_checkpoint -force -noxdef -rename_prefix clk_hdmi_640x480_ clk_hdmi_640x480.dcp

 set ipCachedFiles {}
 write_verilog -force -mode synth_stub -rename_top decalper_eb_ot_sdeen_pot_pi_dehcac_xnilix -prefix decalper_eb_ot_sdeen_pot_pi_dehcac_xnilix_ clk_hdmi_640x480_stub.v
 lappend ipCachedFiles clk_hdmi_640x480_stub.v

 write_vhdl -force -mode synth_stub -rename_top decalper_eb_ot_sdeen_pot_pi_dehcac_xnilix -prefix decalper_eb_ot_sdeen_pot_pi_dehcac_xnilix_ clk_hdmi_640x480_stub.vhdl
 lappend ipCachedFiles clk_hdmi_640x480_stub.vhdl

 write_verilog -force -mode funcsim -rename_top decalper_eb_ot_sdeen_pot_pi_dehcac_xnilix -prefix decalper_eb_ot_sdeen_pot_pi_dehcac_xnilix_ clk_hdmi_640x480_sim_netlist.v
 lappend ipCachedFiles clk_hdmi_640x480_sim_netlist.v

 write_vhdl -force -mode funcsim -rename_top decalper_eb_ot_sdeen_pot_pi_dehcac_xnilix -prefix decalper_eb_ot_sdeen_pot_pi_dehcac_xnilix_ clk_hdmi_640x480_sim_netlist.vhdl
 lappend ipCachedFiles clk_hdmi_640x480_sim_netlist.vhdl

 config_ip_cache -add -dcp clk_hdmi_640x480.dcp -move_files $ipCachedFiles -use_project_ipc -ip [get_ips clk_hdmi_640x480]
}

rename_ref -prefix_all clk_hdmi_640x480_

# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef clk_hdmi_640x480.dcp
create_report "clk_hdmi_640x480_synth_1_synth_report_utilization_0" "report_utilization -file clk_hdmi_640x480_utilization_synth.rpt -pb clk_hdmi_640x480_utilization_synth.pb"

if { [catch {
  file copy -force /home/joco/Documents/cours/FPGA/master/nexys_video/mse_mandelbrot/mse_mandelbrot.runs/clk_hdmi_640x480_synth_1/clk_hdmi_640x480.dcp /home/joco/Documents/cours/FPGA/master/nexys_video/mse_mandelbrot/mse_mandelbrot.srcs/sources_1/ip/clk_hdmi_640x480/clk_hdmi_640x480.dcp
} _RESULT ] } { 
  send_msg_id runtcl-3 error "ERROR: Unable to successfully create or copy the sub-design checkpoint file."
  error "ERROR: Unable to successfully create or copy the sub-design checkpoint file."
}

if { [catch {
  write_verilog -force -mode synth_stub /home/joco/Documents/cours/FPGA/master/nexys_video/mse_mandelbrot/mse_mandelbrot.srcs/sources_1/ip/clk_hdmi_640x480/clk_hdmi_640x480_stub.v
} _RESULT ] } { 
  puts "CRITICAL WARNING: Unable to successfully create a Verilog synthesis stub for the sub-design. This may lead to errors in top level synthesis of the design. Error reported: $_RESULT"
}

if { [catch {
  write_vhdl -force -mode synth_stub /home/joco/Documents/cours/FPGA/master/nexys_video/mse_mandelbrot/mse_mandelbrot.srcs/sources_1/ip/clk_hdmi_640x480/clk_hdmi_640x480_stub.vhdl
} _RESULT ] } { 
  puts "CRITICAL WARNING: Unable to successfully create a VHDL synthesis stub for the sub-design. This may lead to errors in top level synthesis of the design. Error reported: $_RESULT"
}

if { [catch {
  write_verilog -force -mode funcsim /home/joco/Documents/cours/FPGA/master/nexys_video/mse_mandelbrot/mse_mandelbrot.srcs/sources_1/ip/clk_hdmi_640x480/clk_hdmi_640x480_sim_netlist.v
} _RESULT ] } { 
  puts "CRITICAL WARNING: Unable to successfully create the Verilog functional simulation sub-design file. Post-Synthesis Functional Simulation with this file may not be possible or may give incorrect results. Error reported: $_RESULT"
}

if { [catch {
  write_vhdl -force -mode funcsim /home/joco/Documents/cours/FPGA/master/nexys_video/mse_mandelbrot/mse_mandelbrot.srcs/sources_1/ip/clk_hdmi_640x480/clk_hdmi_640x480_sim_netlist.vhdl
} _RESULT ] } { 
  puts "CRITICAL WARNING: Unable to successfully create the VHDL functional simulation sub-design file. Post-Synthesis Functional Simulation with this file may not be possible or may give incorrect results. Error reported: $_RESULT"
}


} else {


if { [catch {
  file copy -force /home/joco/Documents/cours/FPGA/master/nexys_video/mse_mandelbrot/mse_mandelbrot.runs/clk_hdmi_640x480_synth_1/clk_hdmi_640x480.dcp /home/joco/Documents/cours/FPGA/master/nexys_video/mse_mandelbrot/mse_mandelbrot.srcs/sources_1/ip/clk_hdmi_640x480/clk_hdmi_640x480.dcp
} _RESULT ] } { 
  send_msg_id runtcl-3 error "ERROR: Unable to successfully create or copy the sub-design checkpoint file."
  error "ERROR: Unable to successfully create or copy the sub-design checkpoint file."
}

if { [catch {
  file rename -force /home/joco/Documents/cours/FPGA/master/nexys_video/mse_mandelbrot/mse_mandelbrot.runs/clk_hdmi_640x480_synth_1/clk_hdmi_640x480_stub.v /home/joco/Documents/cours/FPGA/master/nexys_video/mse_mandelbrot/mse_mandelbrot.srcs/sources_1/ip/clk_hdmi_640x480/clk_hdmi_640x480_stub.v
} _RESULT ] } { 
  puts "CRITICAL WARNING: Unable to successfully create a Verilog synthesis stub for the sub-design. This may lead to errors in top level synthesis of the design. Error reported: $_RESULT"
}

if { [catch {
  file rename -force /home/joco/Documents/cours/FPGA/master/nexys_video/mse_mandelbrot/mse_mandelbrot.runs/clk_hdmi_640x480_synth_1/clk_hdmi_640x480_stub.vhdl /home/joco/Documents/cours/FPGA/master/nexys_video/mse_mandelbrot/mse_mandelbrot.srcs/sources_1/ip/clk_hdmi_640x480/clk_hdmi_640x480_stub.vhdl
} _RESULT ] } { 
  puts "CRITICAL WARNING: Unable to successfully create a VHDL synthesis stub for the sub-design. This may lead to errors in top level synthesis of the design. Error reported: $_RESULT"
}

if { [catch {
  file rename -force /home/joco/Documents/cours/FPGA/master/nexys_video/mse_mandelbrot/mse_mandelbrot.runs/clk_hdmi_640x480_synth_1/clk_hdmi_640x480_sim_netlist.v /home/joco/Documents/cours/FPGA/master/nexys_video/mse_mandelbrot/mse_mandelbrot.srcs/sources_1/ip/clk_hdmi_640x480/clk_hdmi_640x480_sim_netlist.v
} _RESULT ] } { 
  puts "CRITICAL WARNING: Unable to successfully create the Verilog functional simulation sub-design file. Post-Synthesis Functional Simulation with this file may not be possible or may give incorrect results. Error reported: $_RESULT"
}

if { [catch {
  file rename -force /home/joco/Documents/cours/FPGA/master/nexys_video/mse_mandelbrot/mse_mandelbrot.runs/clk_hdmi_640x480_synth_1/clk_hdmi_640x480_sim_netlist.vhdl /home/joco/Documents/cours/FPGA/master/nexys_video/mse_mandelbrot/mse_mandelbrot.srcs/sources_1/ip/clk_hdmi_640x480/clk_hdmi_640x480_sim_netlist.vhdl
} _RESULT ] } { 
  puts "CRITICAL WARNING: Unable to successfully create the VHDL functional simulation sub-design file. Post-Synthesis Functional Simulation with this file may not be possible or may give incorrect results. Error reported: $_RESULT"
}

}; # end if cached_ip 

if {[file isdir /home/joco/Documents/cours/FPGA/master/nexys_video/mse_mandelbrot/mse_mandelbrot.ip_user_files/ip/clk_hdmi_640x480]} {
  catch { 
    file copy -force /home/joco/Documents/cours/FPGA/master/nexys_video/mse_mandelbrot/mse_mandelbrot.srcs/sources_1/ip/clk_hdmi_640x480/clk_hdmi_640x480_stub.v /home/joco/Documents/cours/FPGA/master/nexys_video/mse_mandelbrot/mse_mandelbrot.ip_user_files/ip/clk_hdmi_640x480
  }
}

if {[file isdir /home/joco/Documents/cours/FPGA/master/nexys_video/mse_mandelbrot/mse_mandelbrot.ip_user_files/ip/clk_hdmi_640x480]} {
  catch { 
    file copy -force /home/joco/Documents/cours/FPGA/master/nexys_video/mse_mandelbrot/mse_mandelbrot.srcs/sources_1/ip/clk_hdmi_640x480/clk_hdmi_640x480_stub.vhdl /home/joco/Documents/cours/FPGA/master/nexys_video/mse_mandelbrot/mse_mandelbrot.ip_user_files/ip/clk_hdmi_640x480
  }
}
