# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/quartus/workspace/LPSC/mse_mandelbrot.srcs/sources_1/ip/blk_mem_iter/blk_mem_iter.xci
# IP: The module: 'blk_mem_iter' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/quartus/workspace/LPSC/mse_mandelbrot.srcs/sources_1/ip/blk_mem_iter/blk_mem_iter_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'blk_mem_iter'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: /home/quartus/workspace/LPSC/mse_mandelbrot.srcs/sources_1/ip/blk_mem_iter/blk_mem_iter.xci
# IP: The module: 'blk_mem_iter' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/quartus/workspace/LPSC/mse_mandelbrot.srcs/sources_1/ip/blk_mem_iter/blk_mem_iter_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'blk_mem_iter'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
